### PR TITLE
Added New Dashboard for Showing Rancher status

### PR DESCRIPTION
**Pull request by abhijeetka**
rancher new setup
This is a new Dashboard added to Grafana. Please find below the details.
1. All Rancher Services
2. All Rancher Stack
3. All Active Rancher Services
4. All Active Rancher Stack
5. Name of all Rancher Services with its Status.

### CODE REVIEW

**Comment by Rucknar** [comment]
Looks good, i'll merge it in which should trigger a rebuild of the 'latest' version of the container on the hub. I'll test it out before I update the catalog entry in the community catalog.

**Comment by abhijeetka** [comment]
Sure, i am also thinking if we can introduce alert manager also to the rancher catalog?

i have the ready set available with me. if you would like to test the same, please let me know.

**Comment by Rucknar** [comment]
Potentially yep. I've considered it before, i wanted to keep the template as simple as possible, would need to look at how we make the configuration of that easy for people new to the products.

**Comment by abhijeetka** [comment]
Hey Edward, have you seen the updated changes?? i was waiting if you can check the changes so that i can start working on the Email and alert manager template.

**Comment by Rucknar** [comment]
Looks good! Thanks @abhijeetka

**Pull request merged**
